# Generated by Django 3.2.19 on 2023-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('animation', 'Animation'), ('horror', 'Horror'), ('action', 'Action'), ('science fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('western', 'Western'), ('documentary', 'Documentary'), ('musical', 'Musical'), ('war', 'War'), ('criminal', 'Criminal'), ('children', 'Children')], default='normal', max_length=32),
        ),
    ]
